version: "3.8"
services:
  traefik:
    restart: unless-stopped
    ports:
      - "90:8080"

  api:
    restart: unless-stopped
    build:
      target: base
    volumes:
      - "./services/api/src:/app/src:ro"
    command: "sh ./wait-for-it.sh redis:6379 mongodb:27017 rabbitmq:5672 -- yarn dev"

  admin:
    restart: on-failure
    build:
      target: base
    volumes:
      - "./services/admin/build:/app/build"
      - "./services/admin/src:/app/src:ro"
    command: 'sh ./wait-for-it.sh redis:6379 mongodb:27017 rabbitmq:5672 -- echo "Start dev server on your machine"'

  mongodb:
    ports:
      - '27017:27017'
    restart: unless-stopped

  redis:
    restart: unless-stopped

  mongodb-express:
    image: 'mongo-express:latest'
    hostname: mongodb-express
    restart: unless-stopped
    ports:
      - '81:8081'
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb

  redis-commander:
    image: 'rediscommander/redis-commander:latest'
    hostname: redis-commander
    restart: unless-stopped
    ports:
      - '83:8081'
    depends_on:
      - redis
    environment:
      - 'REDIS_HOSTS=local:redis:6379'