name: Publish to Digital Ocean

on:
  push:
    branches:
      - develop

jobs:
  publish-do:
    environment: develop
    runs-on: development
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.7.4
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - name: Setup pnpm cache
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: Fetch secrets
        env:
          ENV_SECRETS: ${{ secrets.ENV_SECRETS }}
        run: echo "$ENV_SECRETS" > env.json
      - name: Create service account for storage
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: echo "$GCP_SERVICE_ACCOUNT" > services/api/credentials.json
      - name: Docker Stop Existing Run
        run: sudo make prod-stop
      - name: Docker Build
        run: sudo make prod-build
      - name: Docker Start
        run: sudo make prod-start-detach